### ISSUE TITLE
Interval value

### ISSUE THREAD

**Issue by Gablers** [Bisxsh/WhosThatPixelmon#1]
Hello, I'm just trying out your plugin! 

The interval would've been nice to know :) 

EDIT : If the server restarts while a event is happening, you keep the map.

**Comment by Bisxsh** [comment]
Hey, the intervals by default are set to be randomised between 30-35 minutes. This is configurable via the conf file in your server's config directory however. 

And thank you fo letting me know, I will look into that issue :D

**Comment by Bisxsh** [comment]
This has been fixed in version 1.0.1, thank you for reporting this issue :)
