### ISSUE TITLE
The Plugins doesn´t work

### ISSUE THREAD

**Issue by InmortalPx** [Bisxsh/WhosThatPixelmon#11]
I try to use the plugin but isn´t work, can you help me with the settings?

**Comment by Bisxsh** [comment]
Yup, send me a message on Discord and we can work it out. `Bisxsh#0408`

**Comment by InmortalPx** [comment]
> Yup, send me a message on Discord and we can work it out. `Bisxsh#0408`

i sent you a friend request, but you don't accept me yet.

**Comment by Bisxsh** [comment]
Was solved via Discord, will be closing the issue. Feel free to re-open or message me on discord if you need any more assistance
