### ISSUE TITLE
 That the messages can be changed

### ISSUE THREAD

**Issue by Rexx43** [Bisxsh/WhosThatPixelmon#3]
Hi! 
I saw the plugin and it is very entertaining I would like to add it to my server but they speak Spanish, could you add in the config the option to change the chat messages to translate them? I would greatly appreciate it.

**Comment by SirDoof** [comment]
I'll add: Option to change the prefix too

**Comment by Bisxsh** [comment]
> I'll add: Option to change the prefix too

What do you mean by the prefix may I ask? As in "[Chat Games]"?

**Comment by SirDoof** [comment]
Apologies for the late reply but yes
