### ISSUE TITLE
Possible bug, no rewards given.

### ISSUE THREAD

**Issue by Gablers** [Bisxsh/WhosThatPixelmon#4]
![image](https://user-images.githubusercontent.com/46943194/132215660-393d2037-7d95-4354-883a-9c763a7a417c.png)

They both guessed right, no rewards given. 
If they needed to guess the specific skin, that's impossible for a black image xD

Console said mentioned nothing, not log of any sort.

Thanks, Gab.

**Comment by Gablers** [comment]
I looked again and console did throw an error.
EDIT : https://hastebin.com/ugabajocun.md

**Comment by Bisxsh** [comment]
Hey, it is likely that your config settings are not set up correctly for the rewards. If you have edited these, then it is likely that the formatting is incorrect which caused the problem. Regardless, deleting the config file and running the mod again should fix this.

**Comment by Gablers** [comment]
![image](https://user-images.githubusercontent.com/46943194/132542868-f69ac28a-9da0-4ae6-8654-65b8caa35767.png)
I have also came across this multiple times, I have now fixed the drop rate with the above solution btw.

(it wasn't totodile)

**Comment by Bisxsh** [comment]
This should be fixed in version 1.0.5. Going to close this but feel free to create a new issue if the problem persists.
