### ISSUE TITLE
Another way to keep maps

### ISSUE THREAD

**Issue by SirDoof** [Bisxsh/WhosThatPixelmon#6]
Players are able to pick up an item in their inventory and replace it with the map.

_Thanks for the fixes/updates recently :)_

**Comment by Bisxsh** [comment]
Hey thank you for reporting this. Are you able to provide a video of this bug or offer a detailed explanation as to how it can be replicated?

**Comment by SirDoof** [comment]
Yep, here's a vid
https://gyazo.com/57f27c384938ab5db0e46b4adf613720

**Comment by Bisxsh** [comment]
Added commands to allow players to get and retain maps outside of the minigame in Version 1.2.1. Will be closing this, feel free to open another if you have any other suggestions/reports.
